### ISSUE TITLE
npm install && npm start does not work

### ISSUE THREAD

**Issue by sneak** [steemit/condenser#1088]
in a freshly cloned repo on master:

`npm install && npm start`

```
/Users/sneak/dev/steemit.com/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:176
          throw new ReferenceError(messages.get("pluginUnknown", plugin, loc, i, dirname));
          ^

ReferenceError: Unknown plugin "transform-decorators-legacy" specified in "/Users/sneak/dev/steemit.com/.babelrc" at 1, attempted to resolve relative to "/Users/sneak/dev/steemit.com"
    at /Users/sneak/dev/steemit.com/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:176:17
    at Array.map (native)
    at Function.normalisePlugins (/Users/sneak/dev/steemit.com/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:154:20)
    at OptionManager.mergeOptions (/Users/sneak/dev/steemit.com/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:229:36)
    at OptionManager.init (/Users/sneak/dev/steemit.com/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:374:12)
    at compile (/Users/sneak/dev/steemit.com/node_modules/babel-cli/node_modules/babel-register/lib/node.js:103:45)
    at loader (/Users/sneak/dev/steemit.com/node_modules/babel-cli/node_modules/babel-register/lib/node.js:144:14)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/sneak/dev/steemit.com/node_modules/babel-cli/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)

npm ERR! Darwin 16.4.0
npm ERR! argv "/Users/sneak/Library/Homebrew/Cellar/node/7.4.0/bin/node" "/Users/sneak/Library/Homebrew/bin/npm" "start"
npm ERR! node v7.4.0
npm ERR! npm  v4.0.5
npm ERR! code ELIFECYCLE
npm ERR! Steemit.com@1.0.0 start: `babel-node ./webpack/dev-server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the Steemit.com@1.0.0 start script 'babel-node ./webpack/dev-server.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the Steemit.com package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     babel-node ./webpack/dev-server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs Steemit.com
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls Steemit.com
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/sneak/dev/steemit.com/npm-debug.log
✘-1 ~/dev/steemit.com [master ↓·4|✔] 

```

**Comment by mcifani** [comment]
@sneak I believe this issue could be your npm is outdated. Try `sudo npm install -g npm`, `npm install`, and `npm start` again.

**Comment by sneak** [comment]
now with

> npm ERR! npm  v4.1.2

```
> Steemit.com@1.0.0 start /Users/sneak/dev/steemit.com
> babel-node ./webpack/dev-server.js

/Users/sneak/dev/steemit.com/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:176
          throw new ReferenceError(messages.get("pluginUnknown", plugin, loc, i, dirname));
          ^

ReferenceError: Unknown plugin "transform-decorators-legacy" specified in "/Users/sneak/dev/steemit.com/.babelrc" at 1, attempted to resolve relative to "/Users/sneak/dev/steemit.com"
    at /Users/sneak/dev/steemit.com/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:176:17
    at Array.map (native)
    at Function.normalisePlugins (/Users/sneak/dev/steemit.com/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:154:20)
    at OptionManager.mergeOptions (/Users/sneak/dev/steemit.com/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:229:36)
    at OptionManager.init (/Users/sneak/dev/steemit.com/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:374:12)
    at compile (/Users/sneak/dev/steemit.com/node_modules/babel-cli/node_modules/babel-register/lib/node.js:103:45)
    at loader (/Users/sneak/dev/steemit.com/node_modules/babel-cli/node_modules/babel-register/lib/node.js:144:14)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/sneak/dev/steemit.com/node_modules/babel-cli/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)

npm ERR! Darwin 16.4.0
npm ERR! argv "/Users/sneak/Library/Homebrew/Cellar/node/7.4.0/bin/node" "/Users/sneak/Library/Homebrew/bin/npm" "start"
npm ERR! node v7.4.0
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE
npm ERR! Steemit.com@1.0.0 start: `babel-node ./webpack/dev-server.js`
npm ERR! Exit status 1
```

**Comment by TimCliff** [comment]
I just tried to do a fresh install and I wasn't able to reproduce the error.

Here is what I used to install nvm
```
curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.0/install.sh | bash
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"

nvm install v6
npm install
npm install -g babel-cli
```

After this I did all the config file setup and SQL install.

Then ran:
```
cd ~/steemit.com
npm start
```

Not sure if that helps, but might be worth a try.

**Comment by valzav** [comment]
It might be missing transform-decorators-legacy in shrinkwrap file. I've removed transform-decorators-legacy completely in i18n-refactoring branch.

**Comment by sneak** [comment]
an `npm install transform-decorators-legacy --save-dev` fixed it, afaict. gonna commit that on my branch/PR for now, just remove it from package.json whenever your branch lands.

**Comment by mihai-asumcinei** [comment]
getting the same issue. 

`npm install babel-plugin-transform-decorators-legacy --save`

DIDN'T FIXED IT.

I am now exploring the code, hopefully I will understand what's not working.

Does anyone have any clue on how to fix similar problems?

**Comment by roadscape** [comment]
This is an old report and we're not using `npm` anymore, please open a new ticket if issues persist.
