### ISSUE TITLE
Cannot load condenser instance - fails on sequelize db:migrate

### ISSUE THREAD

**Issue by TimCliff** [steemit/condenser#1494]
I am going through my normal steps to setup a fresh condenser instance, and it is failing on the sequelize db:migrate command. I was able to make the error go away by running `npm install -g mysql2` first, but I've never had to do this before. Do you know what has changed? Also, when I load the website the content loads but the main menu doesn't work. Also, if I click on the login button it just says "Loading" and never loads.

```
Sequelize [Node: 6.11.0, CLI: 2.7.0, ORM: 4.1.0]

Loaded configuration file "config/config.json".
Using environment "development".
Error: Please install mysql2 package manually
    at new ConnectionManager (/home/condenser7/.nvm/versions/node/v6.11.0/lib/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:37:15)
    at new MysqlDialect (/home/condenser7/.nvm/versions/node/v6.11.0/lib/node_modules/sequelize/lib/dialects/mysql/index.js:14:30)
    at new Sequelize (/home/condenser7/.nvm/versions/node/v6.11.0/lib/node_modules/sequelize/lib/sequelize.js:226:20)
    at getSequelizeInstance (/home/condenser7/.nvm/versions/node/v6.11.0/lib/node_modules/sequelize-cli/lib/tasks/db.js:385:12)
    at getMigrator (/home/condenser7/.nvm/versions/node/v6.11.0/lib/node_modules/sequelize-cli/lib/tasks/db.js:394:21)
    at Object.task (/home/condenser7/.nvm/versions/node/v6.11.0/lib/node_modules/sequelize-cli/lib/tasks/db.js:24:14)
    at /home/condenser7/.nvm/versions/node/v6.11.0/lib/node_modules/sequelize-cli/lib/helpers/gulp-helper.js:17:23
    at tryCatcher (/home/condenser7/.nvm/versions/node/v6.11.0/lib/node_modules/sequelize-cli/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/condenser7/.nvm/versions/node/v6.11.0/lib/node_modules/sequelize-cli/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/condenser7/.nvm/versions/node/v6.11.0/lib/node_modules/sequelize-cli/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/condenser7/.nvm/versions/node/v6.11.0/lib/node_modules/sequelize-cli/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/condenser7/.nvm/versions/node/v6.11.0/lib/node_modules/sequelize-cli/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/home/condenser7/.nvm/versions/node/v6.11.0/lib/node_modules/sequelize-cli/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/home/condenser7/.nvm/versions/node/v6.11.0/lib/node_modules/sequelize-cli/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/home/condenser7/.nvm/versions/node/v6.11.0/lib/node_modules/sequelize-cli/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
'db:migrate' errored after 25 ms
    at new ConnectionManager (/home/condenser7/.nvm/versions/node/v6.11.0/lib/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:37:15)
    at new MysqlDialect (/home/condenser7/.nvm/versions/node/v6.11.0/lib/node_modules/sequelize/lib/dialects/mysql/index.js:14:30)
    at new Sequelize (/home/condenser7/.nvm/versions/node/v6.11.0/lib/node_modules/sequelize/lib/sequelize.js:226:20)
    at getSequelizeInstance (/home/condenser7/.nvm/versions/node/v6.11.0/lib/node_modules/sequelize-cli/lib/tasks/db.js:385:12)
    at getMigrator (/home/condenser7/.nvm/versions/node/v6.11.0/lib/node_modules/sequelize-cli/lib/tasks/db.js:394:21)
    at Object.task (/home/condenser7/.nvm/versions/node/v6.11.0/lib/node_modules/sequelize-cli/lib/tasks/db.js:24:14)
    at /home/condenser7/.nvm/versions/node/v6.11.0/lib/node_modules/sequelize-cli/lib/helpers/gulp-helper.js:17:23
    at tryCatcher (/home/condenser7/.nvm/versions/node/v6.11.0/lib/node_modules/sequelize-cli/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/condenser7/.nvm/versions/node/v6.11.0/lib/node_modules/sequelize-cli/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/condenser7/.nvm/versions/node/v6.11.0/lib/node_modules/sequelize-cli/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/condenser7/.nvm/versions/node/v6.11.0/lib/node_modules/sequelize-cli/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/condenser7/.nvm/versions/node/v6.11.0/lib/node_modules/sequelize-cli/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/home/condenser7/.nvm/versions/node/v6.11.0/lib/node_modules/sequelize-cli/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/home/condenser7/.nvm/versions/node/v6.11.0/lib/node_modules/sequelize-cli/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/home/condenser7/.nvm/versions/node/v6.11.0/lib/node_modules/sequelize-cli/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)```

**Comment by surfyogi** [comment]
I plan to create a wiki page for this, or update the readme.

I don't think I understand installation completely; we have some tribal
knowledge that needs to be written down.

I encountered exactly same problem(s) though (partially working condenser
install), and I think this fixed it (see below).

NOTICE: you have a JS error in your chrome console that is the real error
you are searching for a solution to.

b) updated the .babelrc file in top condenser dir

{

  "presets": ["es2015", "stage-0", "react"],

  "plugins": ["transform-runtime", "transform-decorators-legacy"]

}

c) set env:                    <-- may also be an issue for you

touch ~/.bash_profile

edit .bash_profile and add a line:

export SDC_DATABASE_URL="mysql://root:password@localhost/steemit_dev"  *<--
edit here*

source ~/.bash_profile

npm start

OR

I guess you can use yarn, and I don't know much about that yet..

**Comment by sneak** [comment]
Condenser in the current form should work without mysql by using sqlite.  Mysql isn't a hard dependency at this time, I don't think.

**Comment by TimCliff** [comment]
The issues were all resolved by https://github.com/steemit/condenser/pull/1478 . Thanks everyone for your help!
