### ISSUE TITLE
Issues with Vagrant based installation

### ISSUE THREAD

**Issue by nkgokul** [steemit/condenser#1601]
I did a git clone of the project. And then ran `vagrant up `

I got the following error
```

Error: Cannot find module 'steem'
==> default:     at Function.Module._resolveFilename (module.js:470:15)
==> default:     at Function.Module._load (module.js:418:25)
==> default:     at Module.require (module.js:498:17)
==> default:     at require (internal/module.js:20:19)
==> default:     at Object.<anonymous> (/vagrant/server/index.js:4:1)
==> default:     at Module._compile (module.js:571:32)
==> default:     at loader (/vagrant/node_modules/babel-register/lib/node.js:144:5)
==> default:     at Object.require.extensions.(anonymous function) [as .js] (/vagrant/node_modules/babel-register/lib/node.js:154:7)
==> default:     at Module.load (module.js:488:32)
==> default:     at tryModuleLoad (module.js:447:12)
```

Please let me know if I am missing any steps.

**Comment by sneak** [comment]
I was the one who set up Vagrant initially but I haven't had the time to maintain it.  You might start by looking at the Dockerfile and seeing how the setup steps there (used in production) vary from the steps in the Vagrantfile.

In short, Vagrant isn't really supported at the moment, but we will happily accept an PR that fixes it. :)
