### ISSUE TITLE
npm install not working on fresh install - Ubuntu 16.04

### ISSUE THREAD

**Issue by TimCliff** [steemit/condenser#1609]
I am running a fresh install on Ubuntu 16.04 using the instructions in the condenser GitHub "Code" section. When I run `npm install`, it gives an error.

```...

.....

Running post install.js

> steem@0.6.1 prepublish /home/condenser10/condenser/node_modules/steem
> npm run build


> steem@0.6.1 build /home/condenser10/condenser/node_modules/steem
> npm run build-browser && npm run build-node


> steem@0.6.1 build-browser /home/condenser10/condenser/node_modules/steem
> rm -rf dist && NODE_ENV=production webpack && gzip -k -f ./dist/*.js && du -h                                                                                         ./dist/*

Hash: a98b1c86d0e44ce98a4d
Version: webpack 1.15.0
Time: 53ms
    + 1 hidden modules

ERROR in Entry module not found: Error: Cannot resolve 'file' or 'directory' /ho                                                                                        me/condenser10/condenser/node_modules/steem/src/browser.js in /home/condenser10/                                                                                        condenser/node_modules/steem

ERROR in ./test/api.test.js
Module parse failed: /home/condenser10/condenser/node_modules/steem/test/api.tes                                                                                        t.js Unexpected token (18:27)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (18:27)
    at Parser.pp$4.raise (/home/condenser10/condenser/node_modules/steem/node_mo                                                                                        dules/webpack/node_modules/acorn/dist/acorn.js:2221:15)
    at Parser.pp.unexpected (/home/condenser10/condenser/node_modules/steem/node                                                                                        _modules/webpack/node_modules/acorn/dist/acorn.js:603:10)
    at Parser.pp.expect (/home/condenser10/condenser/node_modules/steem/node_mod                                                                                        ules/webpack/node_modules/acorn/dist/acorn.js:597:28)
    at Parser.pp$3.parseExprList (/home/condenser10/condenser/node_modules/steem                                                                                        /node_modules/webpack/node_modules/acorn/dist/acorn.js:2152:16)
    at Parser.pp$3.parseSubscripts (/home/condenser10/condenser/node_modules/ste                                                                                        em/node_modules/webpack/node_modules/acorn/dist/acorn.js:1741:35)
    at Parser.pp$3.parseExprSubscripts (/home/condenser10/condenser/node_modules                                                                                        /steem/node_modules/webpack/node_modules/acorn/dist/acorn.js:1718:17)
    at Parser.pp$3.parseMaybeUnary (/home/condenser10/condenser/node_modules/ste                                                                                        em/node_modules/webpack/node_modules/acorn/dist/acorn.js:1692:19)
    at Parser.pp$3.parseExprOps (/home/condenser10/condenser/node_modules/steem/                                                                                        node_modules/webpack/node_modules/acorn/dist/acorn.js:1637:21)
    at Parser.pp$3.parseMaybeConditional (/home/condenser10/condenser/node_modul                                                                                        es/steem/node_modules/webpack/node_modules/acorn/dist/acorn.js:1620:21)
    at Parser.pp$3.parseMaybeAssign (/home/condenser10/condenser/node_modules/st                                                                                        eem/node_modules/webpack/node_modules/acorn/dist/acorn.js:1597:21)
    at Parser.pp$3.parseExpression (/home/condenser10/condenser/node_modules/ste                                                                                        em/node_modules/webpack/node_modules/acorn/dist/acorn.js:1573:21)
    at Parser.pp$1.parseStatement (/home/condenser10/condenser/node_modules/stee                                                                                        m/node_modules/webpack/node_modules/acorn/dist/acorn.js:727:47)
    at Parser.pp$1.parseBlock (/home/condenser10/condenser/node_modules/steem/no                                                                                        de_modules/webpack/node_modules/acorn/dist/acorn.js:981:25)
    at Parser.pp$3.parseFunctionBody (/home/condenser10/condenser/node_modules/s                                                                                        teem/node_modules/webpack/node_modules/acorn/dist/acorn.js:2105:24)
    at Parser.pp$3.parseArrowExpression (/home/condenser10/condenser/node_module                                                                                        s/steem/node_modules/webpack/node_modules/acorn/dist/acorn.js:2087:10)
    at Parser.pp$3.parseParenArrowList (/home/condenser10/condenser/node_modules                                                                                        /steem/node_modules/webpack/node_modules/acorn/dist/acorn.js:1902:17)
    at Parser.pp$3.parseParenAndDistinguishExpression (/home/condenser10/condens                                                                                        er/node_modules/steem/node_modules/webpack/node_modules/acorn/dist/acorn.js:1870                                                                                        :21)
    at Parser.pp$3.parseExprAtom (/home/condenser10/condenser/node_modules/steem                                                                                        /node_modules/webpack/node_modules/acorn/dist/acorn.js:1796:19)
    at Parser.pp$3.parseExprSubscripts (/home/condenser10/condenser/node_modules                                                                                        /steem/node_modules/webpack/node_modules/acorn/dist/acorn.js:1715:21)
    at Parser.pp$3.parseMaybeUnary (/home/condenser10/condenser/node_modules/ste                                                                                        em/node_modules/webpack/node_modules/acorn/dist/acorn.js:1692:19)
    at Parser.pp$3.parseExprOps (/home/condenser10/condenser/node_modules/steem/                                                                                        node_modules/webpack/node_modules/acorn/dist/acorn.js:1637:21)
    at Parser.pp$3.parseMaybeConditional (/home/condenser10/condenser/node_modul                                                                                        es/steem/node_modules/webpack/node_modules/acorn/dist/acorn.js:1620:21)
    at Parser.pp$3.parseMaybeAssign (/home/condenser10/condenser/node_modules/st                                                                                        eem/node_modules/webpack/node_modules/acorn/dist/acorn.js:1597:21)
    at Parser.pp$3.parseExprList (/home/condenser10/condenser/node_modules/steem                                                                                        /node_modules/webpack/node_modules/acorn/dist/acorn.js:2165:22)
    at Parser.pp$3.parseSubscripts (/home/condenser10/condenser/node_modules/ste                                                                                        em/node_modules/webpack/node_modules/acorn/dist/acorn.js:1741:35)
    at Parser.pp$3.parseExprSubscripts (/home/condenser10/condenser/node_modules                                                                                        /steem/node_modules/webpack/node_modules/acorn/dist/acorn.js:1718:17)
    at Parser.pp$3.parseMaybeUnary (/home/condenser10/condenser/node_modules/ste                                                                                        em/node_modules/webpack/node_modules/acorn/dist/acorn.js:1692:19)
    at Parser.pp$3.parseExprOps (/home/condenser10/condenser/node_modules/steem/                                                                                        node_modules/webpack/node_modules/acorn/dist/acorn.js:1637:21)
    at Parser.pp$3.parseMaybeConditional (/home/condenser10/condenser/node_modul                                                                                        es/steem/node_modules/webpack/node_modules/acorn/dist/acorn.js:1620:21)
    at Parser.pp$3.parseMaybeAssign (/home/condenser10/condenser/node_modules/st                                                                                        eem/node_modules/webpack/node_modules/acorn/dist/acorn.js:1597:21)
gzip: ./dist/*.js: No such file or directory

npm ERR! Linux 3.14.32-xxxx-grs-ipv6-64
npm ERR! argv "/home/condenser10/.nvm/versions/node/v6.11.2/bin/node" "/home/con                                                                                        denser10/.nvm/versions/node/v6.11.2/bin/npm" "run" "build-browser"
npm ERR! node v6.11.2
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! steem@0.6.1 build-browser: `rm -rf dist && NODE_ENV=production webpack                                                                                         && gzip -k -f ./dist/*.js && du -h ./dist/*`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the steem@0.6.1 build-browser script 'rm -rf dist && NODE_ENV                                                                                        =production webpack && gzip -k -f ./dist/*.js && du -h ./dist/*'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the steem package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     rm -rf dist && NODE_ENV=production webpack && gzip -k -f ./dist/*.j                                                                                        s && du -h ./dist/*
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs steem
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls steem
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/condenser10/condenser/node_modules/steem/npm-debug.log

npm ERR! Linux 3.14.32-xxxx-grs-ipv6-64
npm ERR! argv "/home/condenser10/.nvm/versions/node/v6.11.2/bin/node" "/home/con                                                                                        denser10/.nvm/versions/node/v6.11.2/bin/npm" "run" "build"
npm ERR! node v6.11.2
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! steem@0.6.1 build: `npm run build-browser && npm run build-node`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the steem@0.6.1 build script 'npm run build-browser && npm ru                                                                                        n build-node'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the steem package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build-browser && npm run build-node
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs steem
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls steem
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/condenser10/condenser/node_modules/steem/npm-debug.log

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/ch                                                                                        okidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@                                                                                        1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"}                                                                                        )
npm ERR! Linux 3.14.32-xxxx-grs-ipv6-64
npm ERR! argv "/home/condenser10/.nvm/versions/node/v6.11.2/bin/node" "/home/con                                                                                        denser10/.nvm/versions/node/v6.11.2/lib/node_modules/npm/bin/npm-cli.js" "instal                                                                                        l" "--only=dev"
npm ERR! node v6.11.2
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! steem@0.6.1 prepublish: `npm run build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the steem@0.6.1 prepublish script 'npm run build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the steem package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs steem
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls steem
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/condenser10/condenser/node_modules/steem/npm-debug.log
postinstall-build:
  Error: Command failed: sh -c "/home/condenser10/.nvm/versions/node/v6.11.2/bin                                                                                        /node" "/home/condenser10/.nvm/versions/node/v6.11.2/lib/node_modules/npm/bin/np                                                                                        m-cli.js" install --only=dev

......

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@* (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm ERR! Linux 3.14.32-xxxx-grs-ipv6-64
npm ERR! argv "/home/condenser10/.nvm/versions/node/v6.11.2/bin/node" "/home/condenser10/.nvm/versions/node/v6.11.2/bin/npm" "install"
npm ERR! node v6.11.2
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! steem@0.6.1 postinstall: `postinstall-build lib && cross-env scripts/post-install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the steem@0.6.1 postinstall script 'postinstall-build lib && cross-env scripts/post-install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the steem package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     postinstall-build lib && cross-env scripts/post-install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs steem
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls steem
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/condenser10/condenser/npm-debug.log```


----------------

Here is the debut output from condenser/npm-debug.log (full log file can be provided if needed):

```170861 verbose stack Error: steem@0.6.1 postinstall: `postinstall-build lib && cross-env scripts/post-install.js`
170861 verbose stack Exit status 1
170861 verbose stack     at EventEmitter.<anonymous> (/home/condenser10/.nvm/versions/node/v6.11.2/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
170861 verbose stack     at emitTwo (events.js:106:13)
170861 verbose stack     at EventEmitter.emit (events.js:191:7)
170861 verbose stack     at ChildProcess.<anonymous> (/home/condenser10/.nvm/versions/node/v6.11.2/lib/node_modules/npm/lib/utils/spawn.js:40:14)
170861 verbose stack     at emitTwo (events.js:106:13)
170861 verbose stack     at ChildProcess.emit (events.js:191:7)
170861 verbose stack     at maybeClose (internal/child_process.js:891:16)
170861 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
170862 verbose pkgid steem@0.6.1
170863 verbose cwd /home/condenser10/condenser
170864 error Linux 3.14.32-xxxx-grs-ipv6-64
170865 error argv "/home/condenser10/.nvm/versions/node/v6.11.2/bin/node" "/home/condenser10/.nvm/versions/node/v6.11.2/bin/npm" "install"
170866 error node v6.11.2
170867 error npm  v3.10.10
170868 error code ELIFECYCLE
170869 error steem@0.6.1 postinstall: `postinstall-build lib && cross-env scripts/post-install.js`
170869 error Exit status 1
170870 error Failed at the steem@0.6.1 postinstall script 'postinstall-build lib && cross-env scripts/post-install.js'.
170870 error Make sure you have the latest version of node.js and npm installed.
170870 error If you do, this is most likely a problem with the steem package,
170870 error not with npm itself.
170870 error Tell the author that this fails on your system:
170870 error     postinstall-build lib && cross-env scripts/post-install.js
170870 error You can get information on how to open an issue for this project with:
170870 error     npm bugs steem
170870 error Or if that isn't available, you can get their info via:
170870 error     npm owner ls steem
170870 error There is likely additional logging output above.
170871 verbose exit [ 1, true ]```

**Comment by sneak** [comment]
We use `yarn`, not `npm`.  Try that instead.  If this isn't in README, please send a PR. :)
