### ISSUE TITLE
Unhandled rejection Error: not opened

### ISSUE THREAD

**Issue by Jolly-Pirate** [steemit/condenser#1853]
I'm running a local instance of condenser. I keep getting those errors after browsing a few pages then letting the browser idle for a minute or two, then pressing F5. The page hangs for a while, and I end up with a 502 or 504 Bad Gateway. I tried with apache and nginx as reverse proxies, but the problem happens on both. Also, the issue is reproducible on Ubuntu 16.04 and Fedora 26. I setup MySQL, but not tarantool.
P.S. Tested on several RPC's, same problem.
Also, tested straight on condenser at port 8080 without any reverse proxy, the websocket error occurs again. Also happens with steemit/condenser docker image.
```
Unhandled rejection Error: not opened
    at WebSocket.send (/home/server/condenser/node_modules/steem/node_modules/ws/lib/WebSocket.js:355:18)
    at /home/server/condenser/node_modules/steem/lib/api/transports/ws.js:135:19
    at tryCatcher (/home/server/condenser/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/server/condenser/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/server/condenser/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromiseCtx (/home/server/condenser/node_modules/bluebird/js/release/promise.js:606:10)
    at Async._drainQueue (/home/server/condenser/node_modules/bluebird/js/release/async.js:138:12)
    at Async._drainQueues (/home/server/condenser/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/home/server/condenser/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
```
Looking a nginx's error log I find errors like this:
```
2017/10/25 20:01:35 [error] 28116#28116: *9 upstream prematurely closed connection while reading response header from upstream, client: ***.***.***.***, server: myserver.com, request: "GET /created/steemit HTTP/2.0", upstream: "http://127.0.0.1:8080/created/steemit", host: "myserver.com"
```

**Comment by skenan** [comment]
Same error when I am running my cnsteem.com

**Comment by Jolly-Pirate** [comment]
I have a feeling it's because of jussi's optimizations, it broke the regular apache/nginx reverseproxy. I could be wrong though.

**Comment by skenan** [comment]
@Jolly-Pirate I didn't use jussi, you use that locally?

**Comment by Jolly-Pirate** [comment]
I don't use jussi, it's a simple condenser+mysql+nginx/apache setup.

**Comment by KINGdotNET** [comment]
@drakos use "wss://steemd.steemit.com" for your RPC node connection.
It should correct those websocket errors.

**Comment by KINGdotNET** [comment]
What I want to see added is to provide list of RPC nodes. If the first one is not working or slow to respond, the 2nd node will take over automatically if possible.

**Comment by Jolly-Pirate** [comment]
The idea is to use a different RPC node, given the unstability and slowness of wss://steemd.steemit.com.

**Comment by KINGdotNET** [comment]
I agree.

**Comment by KINGdotNET** [comment]
Now I can see this error when I successful logged in and will continue to appear even you logout. 
I restart the service, this error will go away and will re-appear when I login again.

The sign up is broken too.

**Comment by skenan** [comment]
@KINGdotNET This error only happened in lasted condenser.

**Comment by Jolly-Pirate** [comment]
No, the error has been happening since 3-4 days since I started setting it up, so before and after the new UI.

**Comment by KINGdotNET** [comment]
@skenan correction. It is my mistake, got it working. I actually disabled it, stupid me :)
I have it running now, testing the load balancer for https://yehey,org website.

**Comment by skenan** [comment]
@KINGdotNET  you still use the old version, how about trying new one?

**Comment by KINGdotNET** [comment]
@skenan I am working on the 2nd server using the new version of condenser. It seems not stable.
I can browse the site, no issue but every time I connect to sign-up and go back clicking other articles the websockets errors appear. The server will crash eventually.

**Comment by skenan** [comment]
With this error, it's very hard to debug locally.. I feel painful and couldn't contribute to the code. 
@sneak @valzav could you guys please take a look at it? Or give us some advice.

**Comment by bnchdrff** [comment]
this is a known issue caused by the steem js lib. to work around this bug:

```
cd node_modules
rm -r steem
git clone git@github.com:steemit/steem-js steem
cd steem
git checkout ec4439c1319e21ccb4b52a3de3798a37b84b0001
yarn
```

**Comment by KINGdotNET** [comment]
Some of the errors using the new condenser. This will shows right away, when I clicked the new links on the right column e.g. welcome, faq, pick_account, etc. I hope that help.

 <-- GET /pick_account 71e2ed19f7108a971c2734008c
Unhandled rejection Error: not opened
    at WebSocket.send (/home/kingdotnet/condenser/node_modules/steem/node_modules/ws/lib/WebSocket.js:355:18)
    at /home/kingdotnet/condenser/node_modules/steem/lib/api/transports/ws.js:135:19
    at tryCatcher (/home/kingdotnet/condenser/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/kingdotnet/condenser/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/kingdotnet/condenser/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromiseCtx (/home/kingdotnet/condenser/node_modules/bluebird/js/release/promise.js:606:10)
    at Async._drainQueue (/home/kingdotnet/condenser/node_modules/bluebird/js/release/async.js:138:12)
    at Async._drainQueues (/home/kingdotnet/condenser/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/home/kingdotnet/condenser/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
  <-- GET /faq.html 71e2ed19f7108a971c2734008c
Unhandled rejection Error: not opened
    at WebSocket.send (/home/kingdotnet/condenser/node_modules/steem/node_modules/ws/lib/WebSocket.js:355:18)
    at /home/kingdotnet/condenser/node_modules/steem/lib/api/transports/ws.js:135:19
    at tryCatcher (/home/kingdotnet/condenser/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/kingdotnet/condenser/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/kingdotnet/condenser/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromiseCtx (/home/kingdotnet/condenser/node_modules/bluebird/js/release/promise.js:606:10)
    at Async._drainQueue (/home/kingdotnet/condenser/node_modules/bluebird/js/release/async.js:138:12)
    at Async._drainQueues (/home/kingdotnet/condenser/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/home/kingdotnet/condenser/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
  <-- GET /welcome 71e2ed19f7108a971c2734008c
Unhandled rejection Error: not opened
    at WebSocket.send (/home/kingdotnet/condenser/node_modules/steem/node_modules/ws/lib/WebSocket.js:355:18)
    at /home/kingdotnet/condenser/node_modules/steem/lib/api/transports/ws.js:135:19
    at tryCatcher (/home/kingdotnet/condenser/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/kingdotnet/condenser/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/kingdotnet/condenser/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromiseCtx (/home/kingdotnet/condenser/node_modules/bluebird/js/release/promise.js:606:10)
    at Async._drainQueue (/home/kingdotnet/condenser/node_modules/bluebird/js/release/async.js:138:12)
    at Async._drainQueues (/home/kingdotnet/condenser/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/home/kingdotnet/condenser/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)

**Comment by KINGdotNET** [comment]
@bnchdrff I'm trying to download, permission error.
git clone git@github.com:steemit/steem-js steem

Warning: Permanently added 'github.com,192.30.253.112' (RSA) to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

**Comment by bnchdrff** [comment]
you can use https instead of ssh if you don't have your keys set up; change `git@github.com:steemit/steem-js` to `https://github.com/steemit/steem-js`

**Comment by skenan** [comment]
@bnchdrff  why we couldn't fix this bug at steem-js?

**Comment by KINGdotNET** [comment]
@bnchdrff well done! All errors are fixed.
I will continue to test it and share my results here. This will be a 2nd server to be in Europe for my load balancer using the new version of condenser via https://Yehey.org.

Thank you sir.

**Comment by skenan** [comment]
@bnchdrff Can another way to change the package.json from    
 "steem": "github:steemit/steem-js#72a36c835a74f446da47e36feea5d5f1f4dde55b",
to 
 "steem": "github:steemit/steem-js#ec4439c1319e21ccb4b52a3de3798a37b84b0001"?

**Comment by valzav** [comment]
Probably we need to use global webpack instead of `./node_modules/webpack/bin/webpack.js `. Any opinions on this?

**Comment by skenan** [comment]
@Jolly-Pirate  Did you try change the steem version in  package.json, that works for me.

**Comment by Jolly-Pirate** [comment]
@skenan editing the package.json worked flawlessly :)
