### ISSUE TITLE
`Transaction broadcast error.` on posting/commenting

### ISSUE THREAD

**Issue by roadscape** [steemit/condenser#1871]
Recently there have been reports of `Transaction broadcast error.` when submitting a post/comment. Users resubmit the form and find it has been double-posted.

**Comment by Jolly-Pirate** [comment]
Users are still having this issue as of today.

**Comment by lukestokes** [comment]
Very glad you all are working on this. :)

I noticed this again tonight the last time I submitted a root post. Doesn't seem to happen on comments. I was just poking around at `Transaction.js` to see if I could make sense of what was going on, but it's beyond me at this point.

**Comment by Serapium** [comment]
This happened to me today, and I didn't even realize that the blog post had published four times before I came here to see if the submission error I was getting was a known issue or not. So now I have four copies of my blog post submitted to the blockchain. You should at least put a notification or something on the 'Post' page to let people know that if they receive this error message that it's likely their post actually published and they should check their blog page.

**Comment by lukestokes** [comment]
Happens to me with every root post I create. Could we get an update from the developers on when this might be resolved? Thanks!

**Comment by plink01001** [comment]
It's being worked on. Sorry, no ETA as of yet.

**Comment by luzcypher** [comment]
Good luck. Please fix it. This is happening to me every post. I post 1-4 times a day. My friends have been having the same problem too. This issue started 3 weeks ago and is still happening now.

**Comment by noisy** [comment]
I believe, this is still an issue:

Live recording: https://youtu.be/tkLdqM0xrNI

Errors from console:

```
XMLHttpRequest cannot load https://api.steemit.com/. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://steemit.com' is therefore not allowed access. The response had HTTP status code 502.
```

```
TypeError: Network request failed
    at XMLHttpRequest.a.onerror (https://steemit.com/assets/vendor.72053b38bbf36e4273e3.js:1:690359)
From previous event:
    at o.d [as _captureStackTrace] (https://steemit.com/assets/vendor.72053b38bbf36e4273e3.js:1:207626)
    at o._then (https://steemit.com/assets/vendor.72053b38bbf36e4273e3.js:1:239007)
    at o.spread (https://steemit.com/assets/vendor.72053b38bbf36e4273e3.js:1:237600)
    at Object.x.send (https://steemit.com/assets/vendor.72053b38bbf36e4273e3.js:1:700553)
    at https://steemit.com/assets/app.72053b38bbf36e4273e3.js:1:2186224
    at Promise (<anonymous>)
    at t (https://steemit.com/assets/app.72053b38bbf36e4273e3.js:1:35601)
    at https://steemit.com/assets/app.72053b38bbf36e4273e3.js:1:2185718
    at r (https://steemit.com/assets/app.72053b38bbf36e4273e3.js:1:676264)
    at Generator._invoke (https://steemit.com/assets/app.72053b38bbf36e4273e3.js:1:677309)
    at Generator.e.(anonymous function) [as next] (https://steemit.com/assets/app.72053b38bbf36e4273e3.js:1:676443)
    at n (https://steemit.com/assets/app.72053b38bbf36e4273e3.js:1:351305)
    at n (https://steemit.com/assets/app.72053b38bbf36e4273e3.js:1:351650)
    at https://steemit.com/assets/app.72053b38bbf36e4273e3.js:1:352497
```

```
TransactionSaga	broadcastPayload TypeError: Network request failed
    at XMLHttpRequest.a.onerror (https://steemit.com/assets/vendor.72053b38bbf36e4273e3.js:1:690359)
From previous event:
    at o.d [as _captureStackTrace] (https://steemit.com/assets/vendor.72053b38bbf36e4273e3.js:1:207626)
    at o._then (https://steemit.com/assets/vendor.72053b38bbf36e4273e3.js:1:239007)
    at o.spread (https://steemit.com/assets/vendor.72053b38bbf36e4273e3.js:1:237600)
    at Object.x.send (https://steemit.com/assets/vendor.72053b38bbf36e4273e3.js:1:700553)
    at https://steemit.com/assets/app.72053b38bbf36e4273e3.js:1:2186224
    at Promise (<anonymous>)
    at t (https://steemit.com/assets/app.72053b38bbf36e4273e3.js:1:35601)
    at https://steemit.com/assets/app.72053b38bbf36e4273e3.js:1:2185718
    at r (https://steemit.com/assets/app.72053b38bbf36e4273e3.js:1:676264)
    at Generator._invoke (https://steemit.com/assets/app.72053b38bbf36e4273e3.js:1:677309)
    at Generator.e.(anonymous function) [as next] (https://steemit.com/assets/app.72053b38bbf36e4273e3.js:1:676443)
    at n (https://steemit.com/assets/app.72053b38bbf36e4273e3.js:1:351305)
    at n (https://steemit.com/assets/app.72053b38bbf36e4273e3.js:1:351650)
    at https://steemit.com/assets/app.72053b38bbf36e4273e3.js:1:352497
```


@roadscape, @john-g-g: please re-open this issue.

**Comment by TimCliff** [comment]
@noisy the issue is still open.

**Comment by roadscape** [comment]
This was fixed in https://github.com/steemit/jussi and deployed a few hours ago.
