### ISSUE TITLE
condenser `yarn install` requires node-gyp which doesn't work with python 3.6.4 which is current

### ISSUE THREAD

**Issue by sneak** [steemit/condenser#2520]
```
node-pre-gyp ERR! Pre-built binaries not found for sqlite3@3.1.13 and node@8.9.4 (node-v57 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp http 403 status code downloading tarball https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.13/node-v57-android-x64.tar.gz
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@8.9.4 | android | x64
gyp info ok
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@8.9.4 | android | x64
gyp ERR! configure error
gyp ERR! stack Error: Python executable "/data/data/com.termux/files/usr/bin/python" is v3.6.4, which is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
gyp ERR! stack     at PythonFinder.failPythonVersion (/data/data/com.termux/files/home/condenser/node_modules/node-gyp/lib/configure.js:492:19)
gyp ERR! stack     at PythonFinder.<anonymous> (/data/data/com.termux/files/home/condenser/node_modules/node-gyp/lib/configure.js:474:14)
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:267:7)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:925:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
gyp ERR! System Linux 4.4.86-11979-g09b49365a3c4
gyp ERR! command "/data/data/com.termux/files/usr/bin/node" "/data/data/com.termux/files/home/condenser/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/data/data/com.termux/files/home/condenser/node_modules/sqlite3/lib/binding/node-v57-android-x64/node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=/data/data/com.termux/files/home/condenser/node_modules/sqlite3/lib/binding/node-v57-android-x64"
gyp ERR! cwd /data/data/com.termux/files/home/condenser/node_modules/sqlite3
gyp ERR! node -v v8.9.4
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/data/data/com.termux/files/usr/bin/node /data/data/com.termux/files/home/condenser/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/data/data/com.termux/files/home/condenser/node_modules/sqlite3/lib/binding/node-v57-android-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/data/data/com.termux/files/home/condenser/node_modules/sqlite3/lib/binding/node-v57-android-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/data/data/com.termux/files/home/condenser/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:126:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:925:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
node-pre-gyp ERR! System Linux 4.4.86-11979-g09b49365a3c4
node-pre-gyp ERR! command "/data/data/com.termux/files/usr/bin/node" "/data/data/com.termux/files/home/condenser/node_modules/sqlite3/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /data/data/com.termux/files/home/condenser/node_modules/sqlite3
node-pre-gyp ERR! node -v v8.9.4
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! not ok
```

**Comment by sneak** [comment]
Oops, looks like node-gyp only supports python2, which wasn't installed.  We should probably update the readme to mention that `yarn install` will require `python2` and `make` and `clang`.
