### ISSUE TITLE
mac mysql  can't connection

### ISSUE THREAD

**Issue by sailei1** [steemit/condenser#2622]
try   yarn run start
`eady to migrate, create-react-class v15.* is available on npm as a temporary, drop-in replacement. For more info see https://fb.me/react-create-class
Application started on port 8080
type `rs` in console for restarting koa application
Unhandled rejection SequelizeAccessDeniedError: ER_ACCESS_DENIED_ERROR: Access denied for user 'root'@'localhost' (using password: YES)
    at Handshake._callback (/Users/zhangsailei/duozhuan/git/condenser/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:83:20)
    at Handshake.Sequence.end (/Users/zhangsailei/duozhuan/git/condenser/node_modules/mysql/lib/protocol/sequences/Sequence.js:88:24)
    at Handshake.ErrorPacket (/Users/zhangsailei/duozhuan/git/condenser/node_modules/mysql/lib/protocol/sequences/Handshake.js:132:8)
    at Protocol._parsePacket (/Users/zhangsailei/duozhuan/git/condenser/node_modules/mysql/lib/protocol/Protocol.js:279:23)
    at Parser.write (/Users/zhangsailei/duozhuan/git/condenser/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/Users/zhangsailei/duozhuan/git/condenser/node_modules/mysql/lib/protocol/Protocol.js:39:16)
`

**Comment by bnchdrff** [comment]
specify your mysql settings in `SDC_DATABASE_URL`:

```
SDC_DATABASE_URL="mysql://root:yourpassword@127.0.0.1/steemit_dev" NODE_ENV=development ./node_modules/babel-cli/bin/babel-node.js  ./webpack/dev-server.js
```

**Comment by roadscape** [comment]
No more MySQL in this repo 👍
