### ISSUE TITLE
it is not required to run a SQL server except that it is

### ISSUE THREAD

**Issue by marekyggdrasil** [steemit/condenser#2655]
README.md clearly states `is is not required to run a SQL server for development`

https://github.com/steemit/condenser/blob/master/README.md#install-mysql-server

Yet I am not able to run neither development neither production mode without constant attempts to reach `127.0.0.1:3306`.

Could anyone comment on that?

```
$ yarn run production
yarn run v1.5.1
$ NODE_ENV=production node lib/server/index.js
application server starting, please wait.
Worker process started for port 8080
Worker process started for port 8080
Worker process started for port 8080
Worker process started for port 8080
  <-- GET /submit.html a01973aaf22c0aefd92cda6467
  --> GET /submit.html 200 646ms 30.69kB a01973aaf22c0aefd92cda6467
Request took too long! 662ms: GET /submit.html. Number of parallel requests: 1, number of processes: 4
  <-- POST /api/v1/record_event a01973aaf22c0aefd92cda6467
-- /record_event --> ip=::1 uid=a01973aaf22c0aefd92cda6467 type=client_error value=ReferenceError: demotext is not defined | ReferenceError: demotext is not defined
    at t.value (http://localhost:8080/assets/app.bf51c18934f18f4d283c.js:1:103602)
    at l._renderValidatedComponentWithoutOwnerOrContext (http://localhost:8080/assets/vendor.bf51c18934f18f4d283c.js:1:672382)
    at l._renderValidatedComponent (http://localhost:8080/assets/vendor.bf51c18934f18f4d283c.js:1:672509)
    at l.performInitialMount (http://localhost:8080/assets/vendor.bf51c18934f18f4d283c.js:1:668350)
    at l.mountComponent (http://localhost:8080/assets/vendor.bf51c18934f18f4d283c.js:1:667396)
    at Object.mountComponent (http://localhost:8080/assets/vendor.bf51c18934f18f4d283c.js:1:214253)
    at l.performInitialMount (http://localhost:8080/assets/vendor.bf51c18934f18f4d283c.js:1:668510)
    at l.mountComponent (http://localhost:8080/assets/vendor.bf51c18934f18f4d283c.js:1:667396)
    at Object.mountComponent (http://localhost:8080/assets/vendor.bf51c18934f18f4d283c.js:1:214253)
    at v.mountChildren (http://localhost:8080/assets/vendor.bf51c18934f18f4d283c.js:1:663164)
    at v._createInitialChildren (http://localhost:8080/assets/vendor.bf51c18934f18f4d283c.js:1:651859)
    at v.mountComponent (http://localhost:8080/assets/vendor.bf51c18934f18f4d283c.js:1:650073)
    at Object.mountComponent (http://localhost:8080/assets/vendor.bf51c18934f18f4d283c.js:1:214253)
    at v.mountChildren (http://localhost:8080/assets/vendor.bf51c18934f18f4d283c.js:1:663164)
    at v._createInitialChildren (http://localhost:8080/assets/vendor.bf51c18934f18f4d283c.js:1:651859)
    at v.mountComponent (http://localhost:8080/assets/vendor.bf51c18934f18f4d283c.js:1:650073)
  --> POST /api/v1/record_event 200 24ms 15B a01973aaf22c0aefd92cda6467
!!! Can't create web event record { SequelizeConnectionRefusedError: connect ECONNREFUSED 127.0.0.1:3306
    at Handshake._callback (/Users/user/Development/condenser/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:80:20)
    at Handshake.Sequence.end (/Users/user/Development/condenser/node_modules/mysql/lib/protocol/sequences/Sequence.js:88:24)
    at Protocol.handleNetworkError (/Users/user/Development/condenser/node_modules/mysql/lib/protocol/Protocol.js:363:14)
    at Connection._handleNetworkError (/Users/user/Development/condenser/node_modules/mysql/lib/Connection.js:428:18)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  name: 'SequelizeConnectionRefusedError',
  message: 'connect ECONNREFUSED 127.0.0.1:3306',
  parent: 
   { Error: connect ECONNREFUSED 127.0.0.1:3306
    at Object._errnoException (util.js:1021:11)
    at _exceptionWithHostPort (util.js:1043:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1175:14)
    --------------------
    at Protocol._enqueue (/Users/user/Development/condenser/node_modules/mysql/lib/protocol/Protocol.js:145:48)
    at Protocol.handshake (/Users/user/Development/condenser/node_modules/mysql/lib/protocol/Protocol.js:52:23)
    at Connection.connect (/Users/user/Development/condenser/node_modules/mysql/lib/Connection.js:130:18)
    at /Users/user/Development/condenser/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:75:16
    at Promise._execute (/Users/user/Development/condenser/node_modules/bluebird/js/release/debuggability.js:303:9)
    at Promise._resolveFromExecutor (/Users/user/Development/condenser/node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (/Users/user/Development/condenser/node_modules/bluebird/js/release/promise.js:79:10)
    at ConnectionManager.connect (/Users/user/Development/condenser/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:55:10)
    at ConnectionManager.<anonymous> (/Users/user/Development/condenser/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:247:43)
    at ConnectionManager.tryCatcher (/Users/user/Development/condenser/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/user/Development/condenser/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/user/Development/condenser/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/user/Development/condenser/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/user/Development/condenser/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/Users/user/Development/condenser/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Users/user/Development/condenser/node_modules/bluebird/js/release/async.js:143:10)
     code: 'ECONNREFUSED',
     errno: 'ECONNREFUSED',
     syscall: 'connect',
     address: '127.0.0.1',
     port: 3306,
     fatal: true },
  original: 
   { Error: connect ECONNREFUSED 127.0.0.1:3306
    at Object._errnoException (util.js:1021:11)
    at _exceptionWithHostPort (util.js:1043:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1175:14)
    --------------------
    at Protocol._enqueue (/Users/user/Development/condenser/node_modules/mysql/lib/protocol/Protocol.js:145:48)
    at Protocol.handshake (/Users/user/Development/condenser/node_modules/mysql/lib/protocol/Protocol.js:52:23)
    at Connection.connect (/Users/user/Development/condenser/node_modules/mysql/lib/Connection.js:130:18)
    at /Users/user/Development/condenser/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:75:16
    at Promise._execute (/Users/user/Development/condenser/node_modules/bluebird/js/release/debuggability.js:303:9)
    at Promise._resolveFromExecutor (/Users/user/Development/condenser/node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (/Users/user/Development/condenser/node_modules/bluebird/js/release/promise.js:79:10)
    at ConnectionManager.connect (/Users/user/Development/condenser/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:55:10)
    at ConnectionManager.<anonymous> (/Users/user/Development/condenser/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:247:43)
    at ConnectionManager.tryCatcher (/Users/user/Development/condenser/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/user/Development/condenser/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/user/Development/condenser/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/user/Development/condenser/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/user/Development/condenser/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/Users/user/Development/condenser/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Users/user/Development/condenser/node_modules/bluebird/js/release/async.js:143:10)
     code: 'ECONNREFUSED',
     errno: 'ECONNREFUSED',
     syscall: 'connect',
     address: '127.0.0.1',
     port: 3306,
     fatal: true } }
```

**Comment by marekyggdrasil** [comment]
The error

```
ReferenceError: demotext is not defined
```

Was caused by my local debugging, for clarity I `yarn build` again to get rid of it, still attempts to connect to MySQL

```
$ NODE_ENV=production node lib/server/index.js
application server starting, please wait.
Worker process started for port 8080
Worker process started for port 8080
Worker process started for port 8080
Worker process started for port 8080
  <-- GET / a01973aaf22c0aefd92cda6467
  --> GET / 200 912ms 330.84kB a01973aaf22c0aefd92cda6467
Request took too long! 938ms: GET /. Number of parallel requests: 1, number of processes: 4
  <-- POST /api/v1/page_view a01973aaf22c0aefd92cda6467
-- /page_view --> ip=::1 uid=a01973aaf22c0aefd92cda6467 page=/
Error in /page_view api call a01973aaf22c0aefd92cda6467 connect ECONNREFUSED 127.0.0.1:3306
  --> POST /api/v1/page_view 500 110ms 47B a01973aaf22c0aefd92cda6467
  <-- POST /api/v1/login_account a01973aaf22c0aefd92cda6467
-- /login_account --> ip=::1 uid=a01973aaf22c0aefd92cda6467 account=usern
Error in /login_account api call a01973aaf22c0aefd92cda6467 connect ECONNREFUSED 127.0.0.1:3306
  --> POST /api/v1/login_account 500 16ms 47B a01973aaf22c0aefd92cda6467
!!! Can't create web event record { SequelizeConnectionRefusedError: connect ECONNREFUSED 127.0.0.1:3306
    at Handshake._callback (/Users/user/Development/condenser/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:80:20)
    at Handshake.Sequence.end (/Users/user/Development/condenser/node_modules/mysql/lib/protocol/sequences/Sequence.js:88:24)
    at Protocol.handleNetworkError (/Users/user/Development/condenser/node_modules/mysql/lib/protocol/Protocol.js:363:14)
    at Connection._handleNetworkError (/Users/user/Development/condenser/node_modules/mysql/lib/Connection.js:428:18)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  name: 'SequelizeConnectionRefusedError',
  message: 'connect ECONNREFUSED 127.0.0.1:3306',
  parent: 
   { Error: connect ECONNREFUSED 127.0.0.1:3306
    at Object._errnoException (util.js:1021:11)
    at _exceptionWithHostPort (util.js:1043:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1175:14)
    --------------------
    at Protocol._enqueue (/Users/user/Development/condenser/node_modules/mysql/lib/protocol/Protocol.js:145:48)
    at Protocol.handshake (/Users/user/Development/condenser/node_modules/mysql/lib/protocol/Protocol.js:52:23)
    at Connection.connect (/Users/user/Development/condenser/node_modules/mysql/lib/Connection.js:130:18)
    at /Users/user/Development/condenser/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:75:16
    at Promise._execute (/Users/user/Development/condenser/node_modules/bluebird/js/release/debuggability.js:303:9)
    at Promise._resolveFromExecutor (/Users/user/Development/condenser/node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (/Users/user/Development/condenser/node_modules/bluebird/js/release/promise.js:79:10)
    at ConnectionManager.connect (/Users/user/Development/condenser/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:55:10)
    at ConnectionManager.<anonymous> (/Users/user/Development/condenser/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:247:43)
    at ConnectionManager.tryCatcher (/Users/user/Development/condenser/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/user/Development/condenser/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/user/Development/condenser/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/user/Development/condenser/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/user/Development/condenser/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/Users/user/Development/condenser/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Users/user/Development/condenser/node_modules/bluebird/js/release/async.js:143:10)
     code: 'ECONNREFUSED',
     errno: 'ECONNREFUSED',
     syscall: 'connect',
     address: '127.0.0.1',
     port: 3306,
     fatal: true },
  original: 
   { Error: connect ECONNREFUSED 127.0.0.1:3306
    at Object._errnoException (util.js:1021:11)
    at _exceptionWithHostPort (util.js:1043:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1175:14)
    --------------------
    at Protocol._enqueue (/Users/user/Development/condenser/node_modules/mysql/lib/protocol/Protocol.js:145:48)
    at Protocol.handshake (/Users/user/Development/condenser/node_modules/mysql/lib/protocol/Protocol.js:52:23)
    at Connection.connect (/Users/user/Development/condenser/node_modules/mysql/lib/Connection.js:130:18)
    at /Users/user/Development/condenser/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:75:16
    at Promise._execute (/Users/user/Development/condenser/node_modules/bluebird/js/release/debuggability.js:303:9)
    at Promise._resolveFromExecutor (/Users/user/Development/condenser/node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (/Users/user/Development/condenser/node_modules/bluebird/js/release/promise.js:79:10)
    at ConnectionManager.connect (/Users/user/Development/condenser/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:55:10)
    at ConnectionManager.<anonymous> (/Users/user/Development/condenser/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:247:43)
    at ConnectionManager.tryCatcher (/Users/user/Development/condenser/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/user/Development/condenser/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/user/Development/condenser/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/user/Development/condenser/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/user/Development/condenser/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/Users/user/Development/condenser/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Users/user/Development/condenser/node_modules/bluebird/js/release/async.js:143:10)
     code: 'ECONNREFUSED',
     errno: 'ECONNREFUSED',
     syscall: 'connect',
     address: '127.0.0.1',
     port: 3306,
     fatal: true } }
  <-- POST /api/v1/page_view a01973aaf22c0aefd92cda6467
  --> POST /api/v1/page_view 200 1ms 11B a01973aaf22c0aefd92cda6467
  <-- POST /api/v1/page_view a01973aaf22c0aefd92cda6467
-- /page_view --> ip=::1 uid=a01973aaf22c0aefd92cda6467 page=/submit.html
Error in /page_view api call a01973aaf22c0aefd92cda6467 connect ECONNREFUSED 127.0.0.1:3306
  --> POST /api/v1/page_view 500 4ms 47B a01973aaf22c0aefd92cda6467
```

**Comment by roadscape** [comment]
If you patch this file do you still get any errors?
```
--- a/src/server/record_web_event.js
+++ b/src/server/record_web_event.js
@@ -1,6 +1,7 @@
 import { WebEvent, esc } from 'db/models';

 export default function recordWebEvent(ctx, event_type, value) {
+    return;
     if (ctx.state.isBot) return;
     const s = ctx.session;
     const r = ctx.req;
```

**Comment by bnchdrff** [comment]
you can safely ignore the mysql errors -- they do not impede local development

**Comment by marekyggdrasil** [comment]
@roadscape thanks, error is still there but at least it's not crashing

```
application server starting, please wait.
Worker process started for port 8080
Worker process started for port 8080
Worker process started for port 8080
Worker process started for port 8080
  <-- GET /submit.html a01973aaf22c0aefd92cda6467
  --> GET /submit.html 200 216ms 30.69kB a01973aaf22c0aefd92cda6467
Request took too long! 231ms: GET /submit.html. Number of parallel requests: 1, number of processes: 4
  <-- POST /api/v1/page_view a01973aaf22c0aefd92cda6467
-- /page_view --> ip=::1 uid=a01973aaf22c0aefd92cda6467 page=/submit.html
Error in /page_view api call a01973aaf22c0aefd92cda6467 connect ECONNREFUSED 127.0.0.1:3306
  --> POST /api/v1/page_view 500 100ms 47B a01973aaf22c0aefd92cda6467
  <-- POST /api/v1/login_account a01973aaf22c0aefd92cda6467
Error in /login_account api call a01973aaf22c0aefd92cda6467 connect ECONNREFUSED 127.0.0.1:3306
  --> POST /api/v1/login_account 500 12ms 47B a01973aaf22c0aefd92cda6467
```

@bnchdrff sure, if it doesn't matter, just feels pretty unclean to develop with those errors constantly appearing, but I'll keep that in mind

**Comment by roadscape** [comment]
This behavior should be fixed to be more graceful. A speed bump we don't need

**Comment by roadscape** [comment]
Db components have been removed from this repo; this is no longer an issue.
