### ISSUE TITLE
Condenser not creating MySQL tables

### ISSUE THREAD

**Issue by lonnieOST** [steemit/condenser#2710]
Hello,

I have been trying to run Condenser (with MySQL)  and can connect to the MySQL server for which I have created the steemit_dev database but it seems that Condenser is not creating any of the tables even though I have granted all of the permissions according to your documentation on GitHub.

I am getting:
------------------------------------------------------------------------------------
~$ docker run -it --name=condenser2 --env SDC_DATABASE_URL="mysql://root:password@172.17.0.2/steemit_dev" -p 8080:8080 steemit/condenser
yarn run v1.5.1
$ NODE_ENV=production node lib/server/index.js
application server starting, please wait.
Worker process started for port 8080
Worker process started for port 8080
.
.
.
Worker process started for port 8080
  <-- GET / 3c01a53ad8f4d32f881103ae3a
  --> GET / 200 967ms 326.33kB 3c01a53ad8f4d32f881103ae3a
.
.

Error in /login_account api call 3c01a53ad8f4d32f881103ae3a ER_NO_SUCH_TABLE: Table 'steemit_dev.accounts' doesn't exist
  --> POST /api/v1/login_account 500 20ms 72B 3c01a53ad8f4d32f881103ae3a
!!! Can't create web event record { SequelizeDatabaseError: ER_NO_SUCH_TABLE: Table 'steemit_dev.web_events' doesn't exist
    at Query.formatError (/var/app/node_modules/sequelize/lib/dialects/mysql/query.js:175:14)
    at Query._callback (/var/app/node_modules/sequelize/lib/dialects/mysql/query.js:49:21)
    at Query.Sequence.end (/var/app/node_modules/mysql/lib/protocol/sequences/Sequence.js:88:24)
    at Query.ErrorPacket (/var/app/node_modules/mysql/lib/protocol/sequences/Query.js:90:8)
    at Protocol._parsePacket (/var/app/node_modules/mysql/lib/protocol/Protocol.js:279:23)
    at Parser.write (/var/app/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/var/app/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/var/app/node_modules/mysql/lib/Connection.js:103:28)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:264:12)
    at readableAddChunk (_stream_readable.js:251:11)
    at Socket.Readable.push (_stream_readable.js:209:10)
    at TCP.onread (net.js:587:20)
  name: 'SequelizeDatabaseError',
  message: 'ER_NO_SUCH_TABLE: Table \'steemit_dev.web_events\' doesn\'t exist',
  parent: 
   { Error: ER_NO_SUCH_TABLE: Table 'steemit_dev.web_events' doesn't exist
    at Query.Sequence._packetToError (/var/app/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)
    at Query.ErrorPacket (/var/app/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
    at Protocol._parsePacket (/var/app/node_modules/mysql/lib/protocol/Protocol.js:279:23)
    at Parser.write (/var/app/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/var/app/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/var/app/node_modules/mysql/lib/Connection.js:103:28)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:264:12)
    at readableAddChunk (_stream_readable.js:251:11)
    at Socket.Readable.push (_stream_readable.js:209:10)
    at TCP.onread (net.js:587:20)
    --------------------
    at Protocol._enqueue (/var/app/node_modules/mysql/lib/protocol/Protocol.js:145:48)
    at Connection.query (/var/app/node_modules/mysql/lib/Connection.js:208:25)
    at /var/app/node_modules/sequelize/lib/dialects/mysql/query.js:40:21
    at Promise._execute (/var/app/node_modules/bluebird/js/release/debuggability.js:303:9)
    at Promise._resolveFromExecutor (/var/app/node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (/var/app/node_modules/bluebird/js/release/promise.js:79:10)
    at Query.run (/var/app/node_modules/sequelize/lib/dialects/mysql/query.js:39:17)
    at /var/app/node_modules/sequelize/lib/sequelize.js:849:20
    at /var/app/node_modules/retry-as-promised/index.js:39:21
    at Promise._execute (/var/app/node_modules/bluebird/js/release/debuggability.js:303:9)
    at Promise._resolveFromExecutor (/var/app/node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (/var/app/node_modules/bluebird/js/release/promise.js:79:10)
    at retryAsPromised (/var/app/node_modules/retry-as-promised/index.js:29:10)
    at /var/app/node_modules/sequelize/lib/sequelize.js:848:12
    at tryCatcher (/var/app/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/var/app/node_modules/bluebird/js/release/promise.js:512:31)
     code: 'ER_NO_SUCH_TABLE',
     errno: 1146,
     sqlMessage: 'Table \'steemit_dev.web_events\' doesn\'t exist',
     sqlState: '42S02',
     index: 0,
.
.
.
  original: 
   { Error: ER_NO_SUCH_TABLE: Table 'steemit_dev.web_events' doesn't exist
    at Query.Sequence._packetToError (/var/app/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)
    at Query.ErrorPacket (/var/app/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
    at Protocol._parsePacket (/var/app/node_modules/mysql/lib/protocol/Protocol.js:279:23)
    at Parser.write (/var/app/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/var/app/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/var/app/node_modules/mysql/lib/Connection.js:103:28)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:264:12)
    at readableAddChunk (_stream_readable.js:251:11)
    at Socket.Readable.push (_stream_readable.js:209:10)
    at TCP.onread (net.js:587:20)
    --------------------
   --------------------
    at Protocol._enqueue (/var/app/node_modules/mysql/lib/protocol/Protocol.js:145:48)
    at Connection.query (/var/app/node_modules/mysql/lib/Connection.js:208:25)
    at /var/app/node_modules/sequelize/lib/dialects/mysql/query.js:40:21
    at Promise._execute (/var/app/node_modules/bluebird/js/release/debuggability.js:303:9)
    at Promise._resolveFromExecutor (/var/app/node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (/var/app/node_modules/bluebird/js/release/promise.js:79:10)
    at Query.run (/var/app/node_modules/sequelize/lib/dialects/mysql/query.js:39:17)
    at /var/app/node_modules/sequelize/lib/sequelize.js:849:20
    at /var/app/node_modules/retry-as-promised/index.js:39:21
    at Promise._execute (/var/app/node_modules/bluebird/js/release/debuggability.js:303:9)
    at Promise._resolveFromExecutor (/var/app/node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (/var/app/node_modules/bluebird/js/release/promise.js:79:10)
    at retryAsPromised (/var/app/node_modules/retry-as-promised/index.js:29:10)
    at /var/app/node_modules/sequelize/lib/sequelize.js:848:12
    at tryCatcher (/var/app/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/var/app/node_modules/bluebird/js/release/promise.js:512:31)
     code: 'ER_NO_SUCH_TABLE',
     errno: 1146,
     sqlMessage: 'Table \'steemit_dev.web_events\' doesn\'t exist',
     sqlState: '42S02',
     index: 0,
     sql: 'INSERT INTO `web_events` (`id`,`event_type`,`value`,`uid`,`account_name`,`new_session`,`ip`,`refurl`,`user_agent`,`status`,`channel`,`referrer`,`campaign`,`created_at`) VALUES (.......');' },
  sql: 'INSERT INTO `web_events` (`id`,`event_type`,`value`,`uid`,`account_name`,`new_session`,`ip`,`refurl`,`user_agent`,`status`,`channel`,`referrer`,`campaign`,`created_at`) VALUES (/...');' }
  <-- POST /api/v1/page_view 3c01a53ad8f4d32f881103ae3a
  --> POST /api/v1/page_view 200 1ms 11B 3c01a53ad8f4d32f881103ae3a
  <-- POST /api/v1/page_view 3c01a53ad8f4d32f881103ae3a
-- /page_view --> ip=71.200.128.13 uid=3c01a53ad8f4d32f881103ae3a page=/
Error in /page_view api call 3c01a53ad8f4d32f881103ae3a ER_NO_SUCH_TABLE: Table 'steemit_dev.pages' doesn't exist
  --> POST /api/v1/page_view 500 98ms 69B 3c01a53ad8f4d32f881103ae3a
------------------------------------------------------------------------------------

Any ideas on how  to resolve this as I want to setup Condenser with MySQL.

Thanks, in advance.

**Comment by lonnieOST** [comment]
Anybody have any ideas as to where I can get the steemit_dev schema file for the tables that I can load into my MySQL database?

Please help or advise if you can.
Thanks

**Comment by sneak** [comment]
Pretty soon condenser isn’t going to use mysql at all, so this is pretty low priority. All it uses mysql for now is signups (now replaced by faucet), recoveries, and page views (now replaced by overseer).

Condenser should work just fine without a mysql db presently. You can ignore those errors.

**Comment by lonnieOST** [comment]
Great!!!!

So then new registrations and the like will be held on faucet? I'll have to also learn about that and overseer as well since I do not have much experience with them.

Thanks again

**Comment by sneak** [comment]
Yup, faucet handles all registrations now. Overseer is an rpc service that keeps track of user events like page views and other site activity.

**Comment by sneak** [comment]
(both are here on github.)
