### ISSUE TITLE
bulid error,git-rev-sync,Not a valid object name HEAD

### ISSUE THREAD

**Issue by tang1655** [steemit/condenser#2720]
when i  build any download releases(only ` git clone https://github.com/steemit/condenser` can sucess) ,i always meet the same error ,i dont know why ,need help~
> /home/XXX/condenser-0.1.161221/node_modules/git-rev-sync/index.js:20
      throw new Error('[git-rev-sync] failed to execute command:' + result.stderr);
      ^
Error: [git-rev-sync] failed to execute command: fatal: Not a valid object name HEAD

    at _command (/home/XXX/condenser-0.1.161221/node_modules/git-rev-sync/index.js:20:13)
    at Object.tag (/home/XXX/condenser-0.1.161221/node_modules/git-rev-sync/index.js:130:10)
    at Object.<anonymous> (/home/XXX/condenser-0.1.161221/webpack/prod.config.js:17:45)
    at Module._compile (module.js:624:30)

**Comment by roadscape** [comment]
Hi, did this get resolved? If not please reopen.
