### ISSUE TITLE
Error when trying to vote for too many witnesses is not captured and displayed

### ISSUE THREAD

**Issue by lukestokes** [steemit/condenser#3074]
It just shows the spinning animation.

![image](https://user-images.githubusercontent.com/344748/47522847-3b670c00-d85c-11e8-88c8-d69e5ac927b7.png)

```
cause: Error: Assert Exception:voter.witnesses_voted_for < STEEM_MAX_ACCOUNT_WITNESS_VOTES: Account has voted for too many witnesses.
    at new e (https://steemit.com/assets/vendor.76075756e5cb2b4fe718.js:1:432174)
    at https://steemit.com/assets/vendor.76075756e5cb2b4fe718.js:1:431657code: -32000data: {code: 10, name: "assert_exception", message: "Assert Exception", stack: Array(4)}isOperational: truemessage: "Assert Exception:voter.witnesses_voted_for < STEEM_MAX_ACCOUNT_WITNESS_VOTES: Account has voted for too many witnesses."name: "RPCError"stack: "RPCError: Assert Exception:voter.witnesses_voted_for < STEEM_MAX_ACCOUNT_WITNESS_VOTES: Account has voted for too many witnesses.↵    at new e (https://steemit.com/assets/vendor.76075756e5cb2b4fe718.js:1:432174)↵    at https://steemit.com/assets/vendor.76075756e5cb2b4fe718.js:1:431657↵From previous event:↵    at o.p [as _captureStackTrace] (https://steemit.com/assets/vendor.76075756e5cb2b4fe718.js:1:260670)↵    at o._then (https://steemit.com/assets/vendor.76075756e5cb2b4fe718.js:1:292051)↵    at o.spread (https://steemit.com/assets/vendor.76075756e5cb2b4fe718.js:1:290644)↵    at Object.x.send (https://steemit.com/assets/vendor.76075756e5cb2b4fe718.js:1:956720)↵    at https://steemit.com/assets/app.76075756e5cb2b4fe718.js:1:2030220↵    at new Promise (<anonymous>)↵    at new t (https://steemit.com/assets/app.76075756e5cb2b4fe718.js:1:46733)↵    at https://steemit.com/assets/app.76075756e5cb2b4fe718.js:1:2029715↵    at r (https://steemit.com/assets/app.76075756e5cb2b4fe718.js:1:524950)↵    at Generator._invoke (https://steemit.com/assets/app.76075756e5cb2b4fe718.js:1:525995)↵    at Generator.e.(anonymous function) [as next] (https://steemit.com/assets/app.76075756e5cb2b4fe718.js:1:525129)↵    at u (https://steemit.com/assets/app.76075756e5cb2b4fe718.js:1:1990564)↵    at Object.n [as cont] (https://steemit.com/assets/app.76075756e5cb2b4fe718.js:1:1991235)↵    at l (https://steemit.com/assets/app.76075756e5cb2b4fe718.js:1:1991054)↵    at Object.e.cont (https://steemit.com/assets/app.76075756e5cb2b4fe718.js:1:1989555)↵    at u (https://steemit.com/assets/app.76075756e5cb2b4fe718.js:1:1990612)↵    at n (https://steemit.com/assets/app.76075756e5cb2b4fe718.js:1:1991235)↵    at https://steemit.com/assets/app.76075756e5cb2b4fe718.js:1:1992606↵    at r (https://steemit.com/assets/app.76075756e5cb2b4fe718.js:1:401035)↵    at s (https://steemit.com/assets/app.76075756e5cb2b4fe718.js:1:401185)↵    at o (https://steemit.com/assets/app.76075756e5cb2b4fe718.js:1:401084)↵    at Array.<anonymous> (https://steemit.com/assets/app.76075756e5cb2b4fe718.js:1:104676)"__stackCleaned__: true__proto__: Error
(anonymous) @ app.76075756e5cb2b4fe718.js:1
app.76075756e5cb2b4fe718.js:1 TransactionSaga	broadcastPayload i
(anonymous) @ app.76075756e5cb2b4fe718.js:1
app.76075756e5cb2b4fe718.js:1 uncaught at f Error: PANIC: no callback registered to handle error Transaction broadcast error.
    at https://steemit.com/assets/app.76075756e5cb2b4fe718.js:1:33157
    at o (https://steemit.com/assets/app.76075756e5cb2b4fe718.js:1:33237)
    at https://steemit.com/assets/app.76075756e5cb2b4fe718.js:1:2002726
    at https://steemit.com/assets/app.76075756e5cb2b4fe718.js:1:134738
    at s (https://steemit.com/assets/app.76075756e5cb2b4fe718.js:1:132374)
    at https://steemit.com/assets/app.76075756e5cb2b4fe718.js:1:1997431
    at dispatch (https://steemit.com/assets/app.76075756e5cb2b4fe718.js:1:135732)
    at https://steemit.com/assets/app.76075756e5cb2b4fe718.js:1:63869
    at https://steemit.com/assets/app.76075756e5cb2b4fe718.js:1:1992535
    at r (https://steemit.com/assets/app.76075756e5cb2b4fe718.js:1:401035)
    at s (https://steemit.com/assets/app.76075756e5cb2b4fe718.js:1:401185)
    at o (https://steemit.com/assets/app.76075756e5cb2b4fe718.js:1:401084)
    at S (https://steemit.com/assets/app.76075756e5cb2b4fe718.js:1:1992493)
    at c (https://steemit.com/assets/app.76075756e5cb2b4fe718.js:1:1991688)
    at u (https://steemit.com/assets/app.76075756e5cb2b4fe718.js:1:1990627)
    at n (https://steemit.com/assets/app.76075756e5cb2b4fe718.js:1:1991235)
```

**Comment by roadscape** [comment]
Does the issue persist?
