### ISSUE TITLE
SPA throws uncaught exception due to accessing localStorage directly

### ISSUE THREAD

**Issue by sneak** [steemit/condenser#3700]
`Uncaught DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.`

```
Uncaught DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
    at Object.<anonymous> (https://steemit.com/assets/app.7f38b401ec746a4e6664.js:1:353228)
    at e (https://steemit.com/assets/vendor.7f38b401ec746a4e6664.js:1:101)
    at Object.<anonymous> (https://steemit.com/assets/app.7f38b401ec746a4e6664.js:1:743178)
    at e (https://steemit.com/assets/vendor.7f38b401ec746a4e6664.js:1:101)
    at Object.<anonymous> (https://steemit.com/assets/app.7f38b401ec746a4e6664.js:1:499992)
    at e (https://steemit.com/assets/vendor.7f38b401ec746a4e6664.js:1:101)
    at Object.<anonymous> (https://steemit.com/assets/app.7f38b401ec746a4e6664.js:1:498485)
    at e (https://steemit.com/assets/vendor.7f38b401ec746a4e6664.js:1:101)
    at Object.<anonymous> (https://steemit.com/assets/app.7f38b401ec746a4e6664.js:1:473479)
    at Object.<anonymous> (https://steemit.com/assets/app.7f38b401ec746a4e6664.js:1:476072)
    at e (https://steemit.com/assets/vendor.7f38b401ec746a4e6664.js:1:101)
    at Object.<anonymous> (https://steemit.com/assets/app.7f38b401ec746a4e6664.js:1:458628)
    at Object.<anonymous> (https://steemit.com/assets/app.7f38b401ec746a4e6664.js:1:459140)
    at e (https://steemit.com/assets/vendor.7f38b401ec746a4e6664.js:1:101)
    at Object.<anonymous> (https://steemit.com/assets/app.7f38b401ec746a4e6664.js:1:406840)
    at e (https://steemit.com/assets/vendor.7f38b401ec746a4e6664.js:1:101)
```

Accessing `window.localStorage` indiscriminately is not advised.  Per spec, reading or writing to it with localStorage disabled in a browser will throw an exception, not a silent failure.  If you don't catch it, your app breaks.

Per https://michalzalecki.com/why-using-localStorage-directly-is-a-bad-idea/ :

```
function isSupported(getStorage) {
  try {
    const key = "__some_random_key_you_are_not_going_to_use__";
    getStorage().setItem(key, key);
    getStorage().removeItem(key);
    return true;
  } catch (e) {
    return false;
  }
}

isSupported(() => localStorage); // => true | false
```

This way you test for supportedness inside of a try/catch and then can branch on it later, so you're not throwing exceptions in the main app.

**Comment by roadscape** [comment]
Thanks 👍

**Comment by sneak** [comment]
Don't forget to tell your friends:

https://sneak.berlin/20200211/your-website/
